/* tslint:disable */
/* eslint-disable */
/**
 * Cinema API
 * Watch videos together.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TheaterRequest
 */
export interface TheaterRequest {

    /**
     * @type {any}
     * @memberof TheaterRequest
     */
    name: any;

    /**
     * @type {any}
     * @memberof TheaterRequest
     */
    passwd: any;

    /**
     * @type {any}
     * @memberof TheaterRequest
     */
    authReq: any;

    /**
     * @type {any}
     * @memberof TheaterRequest
     */
    seats?: any;
}
