/* tslint:disable */
/* eslint-disable */
/**
 * Cinema API
 * Watch videos together.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ValidationError
 */
export interface ValidationError {

    /**
     * @type {any}
     * @memberof ValidationError
     */
    loc: any;

    /**
     * @type {any}
     * @memberof ValidationError
     */
    msg: any;

    /**
     * @type {any}
     * @memberof ValidationError
     */
    type: any;
}
