/* tslint:disable */
/* eslint-disable */
/**
 * Cinema API
 * Watch videos together.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * OpenapiApi - axios parameter creator
 * @export
 */
export const OpenapiApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Openapi
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openapiApiGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OpenapiApi - functional programming interface
 * @export
 */
export const OpenapiApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Openapi
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async openapiApiGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await OpenapiApiAxiosParamCreator(configuration).openapiApiGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * OpenapiApi - factory interface
 * @export
 */
export const OpenapiApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Openapi
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async openapiApiGet(options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return OpenapiApiFp(configuration).openapiApiGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OpenapiApi - object-oriented interface
 * @export
 * @class OpenapiApi
 * @extends {BaseAPI}
 */
export class OpenapiApi extends BaseAPI {
    /**
     * 
     * @summary Openapi
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OpenapiApi
     */
    public async openapiApiGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return OpenapiApiFp(this.configuration).openapiApiGet(options).then((request) => request(this.axios, this.basePath));
    }
}
