/* tslint:disable */
/* eslint-disable */
/**
 * Cinema API
 * Watch videos together.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { HTTPValidationError } from '../models';
import { TheaterRequest } from '../models';
/**
 * TheatersApi - axios parameter creator
 * @export
 */
export const TheatersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Theater
         * @param {TheaterRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTheaterApiV0TheatersPost: async (body: TheaterRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createTheaterApiV0TheatersPost.');
            }
            const localVarPath = `/api/v0/theaters`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Theaters
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTheatersApiV0TheatersGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v0/theaters`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Query Theater
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryTheaterApiV0TheatersIdGet: async (id: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling queryTheaterApiV0TheatersIdGet.');
            }
            const localVarPath = `/api/v0/theaters/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TheatersApi - functional programming interface
 * @export
 */
export const TheatersApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Theater
         * @param {TheaterRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTheaterApiV0TheatersPost(body: TheaterRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await TheatersApiAxiosParamCreator(configuration).createTheaterApiV0TheatersPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary List Theaters
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTheatersApiV0TheatersGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await TheatersApiAxiosParamCreator(configuration).listTheatersApiV0TheatersGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Query Theater
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async queryTheaterApiV0TheatersIdGet(id: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await TheatersApiAxiosParamCreator(configuration).queryTheaterApiV0TheatersIdGet(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TheatersApi - factory interface
 * @export
 */
export const TheatersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Create Theater
         * @param {TheaterRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTheaterApiV0TheatersPost(body: TheaterRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return TheatersApiFp(configuration).createTheaterApiV0TheatersPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Theaters
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTheatersApiV0TheatersGet(options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return TheatersApiFp(configuration).listTheatersApiV0TheatersGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Query Theater
         * @param {any} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async queryTheaterApiV0TheatersIdGet(id: any, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return TheatersApiFp(configuration).queryTheaterApiV0TheatersIdGet(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TheatersApi - object-oriented interface
 * @export
 * @class TheatersApi
 * @extends {BaseAPI}
 */
export class TheatersApi extends BaseAPI {
    /**
     * 
     * @summary Create Theater
     * @param {TheaterRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TheatersApi
     */
    public async createTheaterApiV0TheatersPost(body: TheaterRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return TheatersApiFp(this.configuration).createTheaterApiV0TheatersPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary List Theaters
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TheatersApi
     */
    public async listTheatersApiV0TheatersGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return TheatersApiFp(this.configuration).listTheatersApiV0TheatersGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Query Theater
     * @param {any} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TheatersApi
     */
    public async queryTheaterApiV0TheatersIdGet(id: any, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return TheatersApiFp(this.configuration).queryTheaterApiV0TheatersIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }
}
